// LOCALHOST

### Get all anime
GET http://localhost:3000/anime

### Get anime by id
GET http://localhost:3000/anime/68c97ded34ff7761a21f6e8c

### Create anime
POST http://localhost:3000/anime HTTP/1.1
content-type: application/json

{
    "title": "Fairy Tail",
    "description": "Fairy Tail is an action-comedy anime about the adventures of Natsu, a fire dragon slayer, and Lucy, a celestial spirit mage, who join the powerful wizard guild, Fairy Tail. Together with their friends, they embark on magical quests, confront dark forces, and uphold the strong bonds of friendship and camaraderie that define their guild. The story blends epic battles with comedic elements, exploring themes of loyalty and found family.",
    "genre": "Fantasy",
    "episodes": "328",
    "rating": "4.8",
    "releaseYear": "2009",
    "streamingPlatform": "Crunchyroll"
}

### Update anime
PUT http://localhost:3000/anime/68c984ba34ff7761a21f6e92 HTTP/1.1
content-type: application/json

{
    "title": "Demon Slayer",
    "description": "Demon Slayer (Kimetsu no Yaiba) is a Japanese manga and anime series following Tanjiro Kamado, a kind-hearted boy who becomes a Demon Slayer after his family is slaughtered by a demon, and his sister Nezuko is transformed into a demon herself. Set in the Taishō era of Japan, Tanjiro joins an organization of demon hunters to avenge his family and find a way to cure his sister, developing his skills and forging bonds with other slayers along the way.",
    "genre": "Shonen",
    "episodes": "26",
    "rating": "4.8",
    "releaseYear": "2019",
    "streamingPlatform": "Netflix"
}

### Delete anime
DELETE http://localhost:3000/anime/68ce70ab742ae87b889a72c2



### Get all profiles
GET http://localhost:3000/profiles

### Get profile by id
GET http://localhost:3000/profiles/68c97a5034ff7761a21f6e86

### Create profile
POST http://localhost:3000/profiles HTTP/1.1
content-type: application/json

{
    "username": "BobTest",
    "email": "bobbytest@gmail.com",
    "favGenre": "Comedy",
    "watchlist": []
}

### Add anime to profile watchlist
POST http://localhost:3000/profiles/68ce711e742ae87b889a72c3/watchlist HTTP/1.1
content-type: application/json

{
    "animeId": "68c97f7634ff7761a21f6e8d"
}

### Remove anime from profile watchlist
DELETE http://localhost:3000/profiles/68ce711e742ae87b889a72c3/watchlist/68c97f7634ff7761a21f6e8d

### Update profile
PUT http://localhost:3000/profiles/68ce711e742ae87b889a72c3 HTTP/1.1
content-type: application/json

{
    "username": "BobTest",
    "email": "bobbytest@gmail.com",
    "favGenre": "Dark Fantasy"
}

### Delete profile
DELETE http://localhost:3000/profiles/68ce711e742ae87b889a72c3
